export {ComponentFloatMenu      as Component} from "./ComponentFloatMenu"
export {ComponentFloatMenuBase  as Base}      from "./ComponentFloatMenuBase"
export {Props}                              from "./Props"
export type {PropsType}                     from "./Props"
export {Schemas}                            from "./Schemas"
export type {SchemasType}                   from "./Schemas"
export {Methods}                            from "./Methods"
export type {MethodsType}                   from "./Methods"
export type {MethodsConfigType,
             MethodsComponentArgs,
             MethodsDataArgs}               from "./Methods"
export {Definition}                         from "./Definition"
export {createFloatMenuStep}                from "./Step"
export {Examples}                           from "./examples"
export type {ComponentFloatMenuExamplesType} from "./examples"
export {DirectionTypes, ShowTypes} from "./Props"
