export {ComponentTabs as Component} from "./ComponentTabs";
export {ComponentTabsBase}           from "./ComponentTabsBase";
export {Definition}                  from "./Definition";
export {Props}                        from "./Props";
export {Schemas}                      from "./Schemas";
export {Methods}                      from "./Methods";
export {Examples}                     from "./examples";
export type {PropsType}               from "./Props";
export type {TabType, TabsViewType}  from "./Props";
export type {SchemasType}            from "./Schemas";
export type {MethodsType, MethodsConfigType} from "./Methods";
export type {ComponentTabsExamplesType}       from "./examples";
