export {ComponentWindowConfirm      as Component} from "./ComponentWindowConfirm"
export {ComponentWindowConfirmBase  as Base}      from "./ComponentWindowConfirmBase"
export {Props}                                    from "./Props"
export type {PropsType}                           from "./Props"
export {Schemas}                                  from "./Schemas"
export type {SchemasType}                         from "./Schemas"
export {Methods}                                  from "./Methods"
export type {MethodsType}                         from "./Methods"
export type {MethodsConfigType,
             MethodsComponentArgs,
             MethodsDataArgs}                     from "./Methods"
export {Definition}                               from "./Definition"
export {createWindowConfirmStep}                  from "./Step"
export {Examples}                                 from "./examples"
export type {ComponentWindowConfirmExamplesType}   from "./examples"
